### ISSUE TITLE
Wrong month display in master branch (1.5dev)

### ISSUE THREAD

**Issue by iainheng** [eternicode/bootstrap-datepicker#1544] opened 2015-08-29 14:43 UTC
I discovered that the month is not displayed correctly. e.g: display July 2015 instead of August 2015 as show in the following screen shot

![datepicker](https://cloud.githubusercontent.com/assets/3263759/9562447/3673962c-4e9f-11e5-885a-dca39ae6064f.jpg)

Here is the jsfiddle to reproduce the issue: http://jsfiddle.net/npyhpcyr/6/

**Comment by hebbet** [comment] 2015-08-30 13:58
possible duplicate of #1533

**Comment by hebbet** [comment] 2015-08-31 16:32
@iainheng can you talk a look at #1533 if that bug is the same as yours?

**Comment by iainheng** [comment] 2015-08-31 18:07
@hebbet It is not same as #1533 as only the title of the month is wrong in this case. It shown July 2015 where it should be showing August 2015 actually. When I click on the day in the picker, the correct date is populated in the text field (only the datepicker month title is wrong). 

Weird enough, I tested again the same jsfiddle just now and it didn't have the same problem now (2015-09-01 here). But it  had the problem the other day 2015-08-29 when I tried it. Maybe the problem is related to August or 31 days month?

**Comment by Sean-214** [comment] 2015-09-01 07:23
@iainheng I discovered too. Your file is different.
In line 909
.text(DPGlobal.formatDate(new Date(year, month), titleFormat, this.o.language));
.text(DPGlobal.formatDate(d, titleFormat, this.o.language));

**Comment by jameskirsop** [comment] 2015-09-05 06:02
I seem to be getting this problem (the wrong month name displayed) regardless of the days in the month.

A fix, that seems to fix the problem for me, fails a bunch of the unit tests on top of 58 that weren't passing using the current source on the master branch. I could very well be doing something wrong, but the unit tests might be broken...

**Comment by hebbet** [comment] 2015-09-05 10:03
why do you use an unstable dev-branch in your projects?

as noted on that or a linked issue, the current release is working fine. 

i will look for the case of that regession in the next few days.

**Comment by jameskirsop** [comment] 2015-09-06 04:06
@hebbet - because 1.4.0 has a display bug in my implementation inside a modal dialog, that the 1.5 dev branch resolves.

**Comment by RobbeR** [comment] 2015-09-07 20:46
This bug is still in the master branch. Sean-214's answer is the solution.

**Comment by hebbet** [comment] 2015-09-08 08:33
@RobbeR yes that bug is still in master branch as this issue here is still open....

**Comment by RobbeR** [comment] 2015-09-08 08:37
@hebbet Yes, sorry, didn't read the dates.

**Comment by acrobat** [comment] 2015-09-21 08:44
Can you guys verify if this issue is resolved in the current master, PR #1503 possibly fixed this issue

**Comment by acrobat** [comment] 2015-09-23 06:47
Closing this as other issues with same problem are fixed, reopen if this is still an issue on the current master! Fixed in #1503

**Closed by acrobat** 2015-09-23 06:47 UTC

**Comment by RobbeR** [comment] 2015-11-12 23:49
It's OK now, thank you for your work
