### ISSUE TITLE
Undefined NaN (01-Jul-2012)

### ISSUE THREAD

**Issue by tysonnero** [eternicode/bootstrap-datepicker#148] opened 2012-07-30 17:39 UTC
If I plug in a date such as 01-Jul-2012 into the date picker, the calendar reads "undefined NAN" and has no values. The value of the textbox reads "NaN/NaN/NaN". The page eventually become unresponsive and must refresh.

I tested this use case with the datepicker on http://www.eyecon.ro/bootstrap-datepicker/, and the same behavior does not happen but rather sets the default date.

**Comment by acrobat** [comment] 2015-01-17 10:56
Closing this issues as I can't reproduce it anymore with the latest release and master

**Closed by acrobat** 2015-01-17 10:56 UTC
Labels: awaiting-feedback
