### ISSUE TITLE
noConflict method not working as intended

### ISSUE THREAD

**Issue by kartik-v** [eternicode/bootstrap-datepicker#1100] opened 2014-09-24 03:05 UTC
The datepicker method is called again in [L1253](https://github.com/eternicode/bootstrap-datepicker/blob/master/js/bootstrap-datepicker.js#L1253) and probably another place or so. So using the picker with a noConflict method like the following is not working:

```js
$.fn.bdatepicker = $.fn.datepicker.noConflict();
$("input").bdatepicker(options); // throws an undefined datepicker error at L1253
```

**Comment by acrobat** [comment] 2015-01-13 07:35
Closing this as it's a duplicate of #736

**Closed by acrobat** 2015-01-13 07:35 UTC
