### ISSUE TITLE
Switching language on demand

### ISSUE THREAD

**Issue by JirkaKrivanek** [eternicode/bootstrap-datepicker#1522] opened 2015-08-12 17:45 UTC
I added this method to allow the switching of the language on demand (instead only at the creation time).

Feel free to add it to you code (and possibly fix, if I am missing some issues with it)...

        setLanguage: function(lang) {
            if (!dates[lang]) {
                lang = lang.split('-')[0];
                if (!dates[lang])
                    lang = defaults.language;
            }
            this.o.language = lang;
            this.fill();
        },

**Comment by hebbet** [comment] 2015-09-10 19:54
duplicate of #362. closing

**Closed by hebbet** 2015-09-10 19:54 UTC
