### ISSUE TITLE
if using noConflict the date range fails because it's calling directly on JQuery

### ISSUE THREAD

**Issue by SafwanHak** [eternicode/bootstrap-datepicker#1112] opened 2014-10-05 16:04 UTC
the following code fails when using noConflict along with DateRangePicker.  

$(this.inputs)
			.datepicker(options) <<<<<<<<<<<<<<
			.bind('changeDate', $.proxy(this.dateUpdated, this));

**Comment by acrobat** [comment] 2015-01-13 07:36
Closing this as a duplicate of #736

**Closed by acrobat** 2015-01-13 07:36 UTC
