### ISSUE TITLE
todayHighlight not showing

### ISSUE THREAD

**Issue by danbuntu** [eternicode/bootstrap-datepicker#1128] opened 2014-10-22 14:29 UTC
I've got the following initialising my datepicker:

    $('.datepicker input').datepicker({
          todayHighlight: true,
          format: 'dd-mm-yyyy'
    });

When I click in the input filed however todays date isn't highlighted. The 'today' class isn't being applied to the date in the picker.

There are no errors showing in the console

**Comment by acrobat** [comment] 2015-01-10 13:04
I can't reproduce this issue with the latest release (1.3.1), see [example](http://jsfiddle.net/g02L8z8y/14/). Closing this for now, please comment/reopen with a jsfiddle example if this still is an issue for you with the latest release!

**Closed by acrobat** 2015-01-10 13:04 UTC
