### ISSUE TITLE
Date Range double execute?

### ISSUE THREAD

**Issue by AlexioVay** [eternicode/bootstrap-datepicker#1418] opened 2015-05-30 15:28 UTC
Hello,

when I'm changing a date in the date-range-input it always executes the code two times.

Example:
$('.datepicker').datepicker({
	format: "mm/yyyy"
}).on('changeDate', function(e){
	console.log(123); 
});

The console outputs 123 two times. Why is that and how can I change this? I want to send ajax-requests after I changed the date on the "from-date"-field or "to-date"-field seperately.

**Comment by hebbet** [comment] 2015-06-10 16:52
duplicate of #912

**Closed by hebbet** 2015-06-10 16:52 UTC
