### ISSUE TITLE
manual selection do not send the right value.

### ISSUE THREAD

**Issue by prbaron** [eternicode/bootstrap-datepicker#936] opened 2014-05-16 12:20 UTC
Hello, I found a weird behavior using this plugin. I would like to know whether it is a bug. I was able to reproduce it on the demo page : http://eternicode.github.io/bootstrap-datepicker/.

**Scenario**

  1. Click on the datepicker input, choose a date with the plugin (ex : 2014-05-16)
  2. Use keyboard to navigate to another date (ex : 2014-05-24), do NOT validate the date.
  3. At this time, the date displayed in the input should be 2014-05-16. Manually change the date by entering a new date with the keyboard (ex : 2014-05-05) by removing/adding number.

**Expected**

The new date, displayed in the input, should be 2014-05-05.

**Result**

The new date, displayed in the input, is 2014-05-24.

**Comment by acrobat** [comment] 2015-01-10 14:11
Closing this issue as I can't reproduce it. If the issue still occurs in the latest release or current master please reopen this issue or open a new issue with a link to this and with a jsfiddle example

**Closed by acrobat** 2015-01-10 14:11 UTC
Labels: can't reproduce
