### ISSUE TITLE
Wrong dutch month name in month view datepicker

### ISSUE THREAD

**Issue by jva91** [eternicode/bootstrap-datepicker#1542] opened 2015-08-28 07:22 UTC
When I'm watching the date 2015-08-28 on my datepicker. The header of the month says Juli in Dutch. But it must be Augustus. When I click on a date, the correct date is printed in the input box. I made a fix  but I don't know if this is an issue in other languages.

file: bootstrap-datepicker.js
line: 910
was:
 .text(DPGlobal.formatDate(new Date(year, month), titleFormat, this.o.language));
replaced with:
.text(DPGlobal.formatDate(new Date(year, (month+1)), titleFormat, this.o.language));

With this fix my month name in the header is displayed correct in dutch

**Comment by hebbet** [comment] 2015-08-28 08:52
can you provide a jsfiddle of that problem?

**Comment by jva91** [comment] 2015-08-31 05:49
How can I set up a fiddle? Never done that.

**Comment by HuBandiT** [comment] 2015-09-03 14:00
please go to https://jsfiddle.net/ and follow the instructions there to recreate the HTML/CSS/JavaScript environment that has the error.

basically, paste the bootstrap-datepicker JS file and bootstrap-datepicker locale JS files into the JavaScript pane (or import them as external resources on the left under External Resources), then paste the HTML into the HTML pane, and make sure you are able to reproduce the problem (don't forget to click on Run on the top after each edit). try to make your fiddle as small and simple as possible, while still able to reproduce the problem.

once you are successful at reproducing the problem, save the jsfiddle (Save button on top), and then paste the URL of the saved fiddle here for developers to take a look.

write your instructions on how to reproduce the problem into the fiddle somewhere (e.g. into the HTML as text to be displayed in the Result pane, or HTML comments if you make them easy to see in the HTML source)

**Comment by jva91** [comment] 2015-09-04 06:03
Thanks for your explanation

https://jsfiddle.net/jva91/tqdsbko5/

The current date is september but the datepicker shows augustus

**Comment by hebbet** [comment] 2015-09-04 06:14
possible duplicate of #1533

**Comment by acrobat** [comment] 2015-09-04 06:20
Thanks for the example @jva91! This is indeed something we need to fix before 1.5 goes out!

**Comment by acrobat** [comment] 2015-09-21 08:44
Can you verify if this issue is resolved in the current master, PR #1503 possibly fixed this issue

**Comment by jva91** [comment] 2015-09-21 08:53
Tested and now its okay. The right month is printed.

**Comment by acrobat** [comment] 2015-09-21 08:54
Great! Thanks for the feedback @jva91!

Fixed in #1503

**Closed by acrobat** 2015-09-21 08:54 UTC
Labels: awaiting-feedback

**Comment by dev-sumesh** [comment] 2015-10-06 11:53
Perfect! This is working fine. Thanks @jva91
