### ISSUE TITLE
Freezing / Hanging on IE9 / IE10

### ISSUE THREAD

**Issue by ScottBaxter1** [eternicode/bootstrap-datepicker#799] opened 2014-01-27 22:55 UTC
Hey Guys,

I seem to have an intermittent problem on IE. A few of my users have reported that when they are selecting a date using the datepicker() it basically freezes and to get the page back they have to refresh which in turn loses all their information.

It only seems to happen on IE and works perfectly in Chrome / Firefox.

Has anyone else had this problem?

**Comment by acrobat** [comment] 2015-01-10 14:10
Closing this issue as I can't reproduce it. If the issue still occurs in the latest release or current master please comment/reopen with a jsfiddle example

**Closed by acrobat** 2015-01-10 14:10 UTC
Labels: can't reproduce, IE
