### ISSUE TITLE
Manually entering values on Range input is broken

### ISSUE THREAD

**Issue by lord-xeon** [eternicode/bootstrap-datepicker#866] opened 2014-03-27 13:02 UTC
I can reproduce this with consistency on the [online demo](http://eternicode.github.io/bootstrap-datepicker/?markup=range&format=&weekStart=&startDate=&endDate=&startView=0&minViewMode=0&todayBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&keyboardNavigation=on&forceParse=on#sandbox)

Basically, when in Range mode, if you try and type in a date it will not work correctly.

1. Enter 2/2/2013 into the start date field (start date field is formatted to 02/02/2013)
2. TAB into the End date field
3. Enter 3/3/2013 into the End date field
4. Notice that the start date field now shows 03/03/2

It seems to happen as soon as you add the first digit of the year in the end date.

Additionally, if you try and manually delete the date string (in the start, or end date field), as soon as the year is removed, the date field automatically gets populated with today's date.

Neither of the above issues are present in a regular, singular datepicker, only the range.

**Comment by chappoo** [comment] 2015-03-26 01:12
Agreed this is an issue for us too.  Workaround at the moment is to specify a startDate of 01/01/1900 (or as appropriate).

http://bootstrap-datepicker.readthedocs.org/en/latest/options.html#startdate

**Comment by DMcNamara** [comment] 2015-05-04 14:38
+1. This is still an annoying issue, the workaround isn't that bad, but a fix would still be awesome.

**Comment by hebbet** [comment] 2015-05-04 17:54
feel free to provide an PR ;)

**Comment by steffendietz** [comment] 2015-09-11 11:21
This seems to be a duplicate of #721

**Comment by hebbet** [comment] 2015-09-12 10:50
thanks, closing that one.

**Closed by hebbet** 2015-09-12 10:50 UTC
Labels: bug
