### ISSUE TITLE
Calling "clearDates" does not clear the "viewDate"

### ISSUE THREAD

**Issue by rpiller** [eternicode/bootstrap-datepicker#1433] opened 2015-06-17 12:14 UTC
I am calling the "clearDates" method to completely reset a date picker control: $('.js-date-picker').datepicker('clearDates');

For example, today is 6/17/2015 and I selected 4/1/2015 in the date picker control. After calling "clearDates" the control is blank but when I click on the control and the calendar view pops open, the April 2015 dates are shown. I expect so see the June 2015 dates.

**Comment by Azaret** [comment] 2015-06-17 18:54
I guess it's intended, `clearDates`is meant to clear dates.

Now I guess we can add some `resetView` method.

**Comment by Azaret** [comment] 2015-06-17 20:07
After looking up to implant such method, I notice that calling `update` without argument does the trick.

**Comment by Azaret** [comment] 2015-06-17 20:17
I should add that it is on the next release, it's actually a duplicate of #1370.

**Comment by rpiller** [comment] 2015-06-17 23:05
Excellent. Thank you for your quick response.

**Comment by acrobat** [comment] 2015-06-18 06:51
Thanks @Azaret for the feedback, closing this a duplicate of #1370

**Closed by acrobat** 2015-06-18 06:51 UTC
