### ISSUE TITLE
Uncaught ReferenceError: jQuery is not defined(anonymous function) @ bootstrap-datepicker.ru.js:15

### ISSUE THREAD

**Issue by fazliddin** [eternicode/bootstrap-datepicker#1675] opened 2015-11-14 05:20 UTC
My jquery version is 1.11.3

**Comment by acrobat** [comment] 2015-11-14 09:10
Can you provide a jsfiddle example to display the problem? Looks like jquery is not yet loaded

**Comment by fazliddin** [comment] 2015-11-14 09:41
jQuery is loaded, I can see it. I am using this component from yiibooster and bootstrap-datetimepicker.js date is 2013-09-12. but i am using 1.11.3 may be this problem

**Comment by fazliddin** [comment] 2015-11-14 10:00
actually problem appears on chrome, but not in firefox. I am using debian 8.

**Comment by acrobat** [comment] 2015-11-14 17:10
If you say bootstrap-datetimepicker that is another library (https://github.com/Eonasdan/bootstrap-datetimepicker) 

Otherwise can you provide a jsfiddle to show us the exact problem?

**Comment by acrobat** [comment] 2015-11-29 19:33
Closing this for now, leave a comment if the problem is with this datepicker

**Closed by acrobat** 2015-11-29 19:33 UTC
