### ISSUE TITLE
expanded width in ie8

### ISSUE THREAD

**Issue by DavBR** [eternicode/bootstrap-datepicker#143] opened 2012-07-23 13:13 UTC
in ie8 the table is expanded, i has fixed putting this *width: auto in .datepicker table

**Comment by acrobat** [comment] 2015-01-10 14:10
Closing this issue as I can't reproduce it. If the issue still occurs in the latest release or current master please comment/reopen with a jsfiddle example

**Closed by acrobat** 2015-01-10 14:10 UTC
Labels: can't reproduce, IE
