### ISSUE TITLE
Change fires even when no date is changed.

### ISSUE THREAD

**Issue by nightsurge** [eternicode/bootstrap-datepicker#1073] opened 2014-09-04 16:04 UTC
This is the biggest annoyance of this datepicker. It fires "Change" even when I make no date changes.

Example: I click the calendar, but decide I don't need to change the date, so I close the calendar. This triggers a "Change" event even though the previous date that was entered in the field had not changed! We do a lot of processing on change events and these extra change events can be costly. Any thoughts on handling this? I currently am using the bootstrap-datepicker-rails gem, but am not apposed to using the files manually and tweaking.

**Comment by hebbet** [comment] 2015-06-10 16:51
duplicate of #912

**Closed by hebbet** 2015-06-10 16:51 UTC
