### ISSUE TITLE
Not translate "Months" title in months view

### ISSUE THREAD

**Issue by vbotingnon** [eternicode/bootstrap-datepicker#1704] opened 2015-12-07 01:46 UTC

**Comment by acrobat** [comment] 2015-12-07 09:42
Can you give some more context (and/or example) on what you try to achieve?

**Comment by vbotingnon** [comment] 2015-12-07 10:07
Sorry,

Configuration:
$('#sandbox-container div').datepicker({
    maxViewMode: 1,
    todayBtn: true,
    language: "pt-BR"
});

![git](https://cloud.githubusercontent.com/assets/13349300/11624232/91d8cbaa-9cb9-11e5-81b1-8bddcc41dacd.png)

**Comment by acrobat** [comment] 2015-12-07 10:10
Ah yes! So the issue is not that the key should be translated but that it's not translated but it should be translated?

**Comment by vbotingnon** [comment] 2015-12-07 10:14
Sorry about my English...

The correct is that word be translated like the Today button

**Comment by acrobat** [comment] 2015-12-07 10:15
Ok, issue is clear now! I will fix this for the coming releases

**Comment by acrobat** [comment] 2015-12-08 18:25
I've fixed the issue in #1708, can you provide the translation for "months" in pt-BR? Then I will add it to the PR

**Comment by acrobat** [comment] 2015-12-19 18:41
Fixed in #1727

**Closed by acrobat** 2015-12-19 18:41 UTC
Labels: bug, translations
