### ISSUE TITLE
Datepicker top vertical position

### ISSUE THREAD

**Issue by smartapant** [eternicode/bootstrap-datepicker#1364] opened 2015-04-09 14:29 UTC
I have this markup:

    <div class="col-md-7">
        <input id="date-field1" class="form-control date-picker" type="text" name="in-  place-date" value=""  placeholder="Enter Date">
        <span class="help-block">Selects some date</span>
    </div>

So, when i use 

    widgetPositioning: {
        vertical: 'top'
    }

the datepicker is positioned not above the input but somewhere below it, after some research i found out that 

    widget.css({
        top: vertical === 'top' ? 'auto' : position.top + element.outerHeight(),
        bottom: vertical === 'top' ? position.top + element.outerHeight() : 'auto',
        left: horizontal === 'left' ? parent.css('padding-left') : 'auto',
        right: horizontal === 'left' ? 'auto' : parent.width() - element.outerWidth()
    });

this code could ignore help's block height.

**Comment by clemens** [comment] 2015-04-14 13:44
I can confirm that the positioning is off since the update to 1.4.0 – see screenshot. With 1.3.1, everything's fine.

![screen shot 2015-04-14 at 15 43 20](https://cloud.githubusercontent.com/assets/3749/7137900/174d8d82-e2bd-11e4-8265-832872d5d7f4.png)

**Comment by clemens** [comment] 2015-04-14 13:47
Similarly odd positioning with slightly different settings.

![screen shot 2015-04-14 at 15 46 20](https://cloud.githubusercontent.com/assets/3749/7137957/7c70a08c-e2bd-11e4-8ae6-8a2ee1843da3.png)

**Comment by yoyos** [comment] 2015-04-15 14:12
My problem on v1.4.0:

![image](https://cloud.githubusercontent.com/assets/1993859/7160561/3592d55e-e38a-11e4-9d5d-0666e3113eac.png)

**Comment by darbula** [comment] 2015-07-20 14:04
Same issue as @yoyos here, his PR fixes the issue.

**Comment by hebbet** [comment] 2015-09-13 18:18
seems to be fixed with f08ad04, closing.

**Closed by hebbet** 2015-09-13 18:18 UTC

**Comment by akluthe** [comment] 2015-11-06 14:57
I downloaded the most recent copy of 1.5.0 from the site proper. I'm having this issue. Where can I get the version that has it fixed? Pulling from repo?

**Comment by acrobat** [comment] 2015-11-06 14:59
Commit  f08ad04 was included in 1.5.0. IF you still have an problem, please create an issue!

**Comment by akluthe** [comment] 2015-11-06 15:21
Sure, but is the link to download 1.5.0 located at:

https://github.com/eternicode/bootstrap-datepicker/releases/download/v1.5.0/bootstrap-datepicker-1.5.0-dist.zip 

Is this the 1.5.0 that contains the fix? I see stuff in the 1.5.0 branch that was updated only hours ago. I'm a bit confused where to get the proper release.

**Comment by acrobat** [comment] 2015-11-06 15:22
oh you mean the 1.5 branch, no that only is not yet released (no date yet, but soon). If you want thoses fixes already you should pull from source!

**Comment by akluthe** [comment] 2015-11-06 15:26
Gotcha, 

![image](https://cloud.githubusercontent.com/assets/2624953/11000608/5e1ed55c-8468-11e5-90ea-5cfe1c0af366.png)

This and the included in 1.5.0 made me think I was getting the most current stable release. Pull from 1.5 branch source should fix my positioning issues?

**Comment by acrobat** [comment] 2015-11-06 15:27
No the commit mentioned above is already included in the 1.5.0 release. The 1.5 branch is the current work on the 1.5.1 bugfix release

But if the commit fixes this issue , it should be fixed in 1.5.0

**Comment by akluthe** [comment] 2015-11-06 15:30
Ok, ill do some more investigating and open another issue if I can get some more info on the problem. I was just trying to make sure I had the right stuff in hand at the moment before opening another one. There are quite a few CSS files too that I wasn't sure which to use, but I see that's been addressed in another issue as something to be added to the docs in the future.

**Comment by abeverley** [comment] 2015-11-13 19:04
See also #1662

**Comment by bradykey** [comment] 2015-12-10 17:36
Definitely has something to do with margins existing in a parent div that the datepicker control is a child of. Like @yoyos, if you get rid of the `appendOffset` subtraction adjustments to the `var left = offset.left` and `top = offset.top` declarations in the javascript, then the offset is no longer an issue. I could see how setting the `data-date-container` property using the lazy loading data-api correctly could make this thing work without needing to change the JS, but I couldn't figure it out.

**Comment by ChristfriedBalizou** [comment] 2016-04-08 16:05
Why is this issue is close ? I'm using "**v1.6.0**"  have the Pop-up position issue. can you re-open the issue please ?

**Comment by David-Bascom** [comment] 2016-04-14 11:18
Same problem here – not fixed yet.

**Comment by shihao316558512** [comment] 2016-04-22 03:00
+1

**Comment by nakazye** [comment] 2016-05-05 12:38
This issue resolved with below PR In my environment. Can you merge this PR?
https://github.com/eternicode/bootstrap-datepicker/pull/1371

**Comment by codymullins** [comment] 2016-05-06 19:16
@nakazye that fixes my issue as well

**Comment by StrongLucky** [comment] 2016-06-15 10:55
I also had the Problem with wrong offset.

I had margin-top on the **body element**. On **change margin-top to padding-top** the datepicker works fine with offset.

Dont like to change the code of a plugin. Maybee the developer should have a look at this problem ;)

**Comment by DutchKev** [comment] 2016-09-07 19:30
@StrongLucky, that fixed it for me to..
